ANSIBLE_GROUPS = {
              "nodes" => ["node1", "node2"],
              "all_groups:children" => ["nodes"]
            }


Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.define "node1" do |node1|
        node1.vm.network "private_network", ip: "192.168.33.10"
        node1.vm.hostname = "node1"
        node1.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yml"
            ansible.groups = ANSIBLE_GROUPS
            ansible.limit = "all"
        end
    end
end
